### ISSUE TITLE
Aderyn Hackathon reward address

### ISSUE THREAD

**Issue by alexroan** [gr4yha7/cartesi-wallet-template#36]
Hey @gr4yha7 !

We're trying to reach you to get an address to send your Hackathon reward to!

Let me know where you'd like us to send it :)

**Comment by gr4yha7** [comment]
Hi @alexroan. Thanks for reaching out, you can send it to this address `0xB08e92D4a03784735a93251A64e145B350228C22`.

**Comment by gr4yha7** [comment]
@alexroan Also, i'd regret it if i didn't at least try to shoot my shot but i'd love to work on Aderyn full-time, if possible.

**Comment by alexroan** [comment]
Paid here: https://etherscan.io/tx/0x2296955b1a2d4a7f77b356c30c6f51a430a5d464b0be60e652bb5cb7b7e19a7d :)

**Comment by gr4yha7** [comment]
> Paid here: https://etherscan.io/tx/0x2296955b1a2d4a7f77b356c30c6f51a430a5d464b0be60e652bb5cb7b7e19a7d :)

Received with many thanks! :)
